name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    strategy:
      matrix:
        python: [3.11.9]
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Poppler (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y poppler-utils

      - name: Install Poppler (macOS)
        if: runner.os == 'macOS'
        run: brew install poppler

      - name: Test declaration
        run: |
          for file in docs/*; do python3 docsum.py ${file}; done


# name: tests

# on:
#   push:
#     branches: ['*']
#   pull_request:
#     branches: ['*']

# jobs:
#   tests:
#     strategy:
#       matrix:
#         python: [3.11.9]
#     runs-on: ubuntu-latest
#     env:
#       GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python ${{matrix.python}}
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{matrix.python}}
#       - name: install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#       - name: Install Poppler (Linux)
      # if: runner.os == 'Linux'
#       run: sudo apt-get install -y poppler-utils
      
#       - name: Install Poppler (macOS)
#       if: runner.os == 'macOS'
#       run: brew install poppler

#       - name: test declaration
#         run: |
#           for file in docs/*; do python3 docsum.py ${file}; done